# Generated by Django 5.2 on 2025-04-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['department', 'course_number']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='major',
        ),
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='socials',
            field=models.JSONField(blank=True, default=dict, help_text='e.g., {"instagram": "username", "snapchat": "username", "x": "handle"}', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_in_school',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate'), ('OT', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'course_number', 'name')},
        ),
        migrations.AddField(
            model_name='profile',
            name='majors',
            field=models.ManyToManyField(blank=True, to='api.major'),
        ),
        migrations.AddField(
            model_name='profile',
            name='minors',
            field=models.ManyToManyField(blank=True, to='api.minor'),
        ),
    ]
