# Generated by Django 5.2 on 2025-04-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_managers_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalityquestion',
            name='domain',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='personalityquestion',
            name='facet',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='personalityquestion',
            name='reverse_scale',
            field=models.BooleanField(default=False),
        ),
    ]
