# Generated by Django 5.2 on 2025-04-27 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('user2_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user1', 'is_deleted', 'expires_at'], name='api_connect_user1_i_22ee77_idx'), models.Index(fields=['user2', 'is_deleted', 'expires_at'], name='api_connect_user2_i_b264de_idx'), models.Index(fields=['created_at'], name='api_connect_created_9cdb48_idx'), models.Index(fields=['expires_at'], name='api_connect_expires_a49097_idx')],
                'constraints': [models.UniqueConstraint(fields=('user1', 'user2'), name='unique_connection_users'), models.CheckConstraint(condition=models.Q(('user1', models.F('user2')), _negated=True), name='prevent_self_connection')],
            },
        ),
    ]
